x=[1,2,-1,3,-2];
n=0:length(x)-1;
d=2;
y=n.*(x.^2);
xd=[zeros(1,d),x];
disp(length(n));
nd=0:length(xd)-1;
xp=[x,zeros(1,d)];
yp=nd.*(xd.^2);
disp(' the otput sequence yp is :');
disp(yp);
yd=[zeros(1,d),y];
disp(' the otput sequence yd is :');
disp(yd);
if(yp==yd)
    disp('y1==y2. hence the system is time  inveriant');
else
    disp('y1~=y2 . hence the system is time veriant');
end
subplot(3,2,1);
stem(n,x);
xlabel("time");
ylabel("amplitude");
title("  input sequence(4D3)");
subplot(3,2,2);
stem(n,y);
xlabel("time");
ylabel("amplitude");
title(" output sequence(4D3)");
subplot(3,2,3);
stem(nd,xd);
xlabel("time");
ylabel("amplitude");
title(" input delay by 2 units(4D3)");
subplot(3,2,4);
stem(nd,xp);
xlabel("time");
ylabel("amplitude");
title(" dummy");
subplot(3,2,5);
stem(nd,yp);
xlabel("time");
ylabel("amplitude");
title(" response to be input delay(4D3)");
subplot(3,2,6);
stem(nd,yd);
xlabel("time");
ylabel("amplitude");
title(" delayed output response(4D3)");
